# ============================================================
#  MkDocs Configuration for Overleaf Toolkit Essential
#  Author: Md. Fahim Bin Amin
#  Description: Documentation configuration for MkDocs Material
# ============================================================

site_name: Overleaf Toolkit Essential
site_description: Automation toolkit for managing local Overleaf installations
site_author: Md. Fahim Bin Amin
site_url: https://fahimfba.github.io/overleaf-toolkit-essential
repo_url: https://github.com/FahimFBA/overleaf-toolkit-essential
repo_name: FahimFBA/overleaf-toolkit-essential
edit_uri: edit/main/docs/   # Enables “Edit on GitHub” links

# ------------------------------------------------------------
#  Theme Configuration
# ------------------------------------------------------------
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png 
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: Fira Code

# ------------------------------------------------------------
#  Navigation Structure
# ------------------------------------------------------------
nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Maintenance: maintenance.md
  - Troubleshooting: troubleshooting.md
  - Architecture: architecture.md
  - Reference:
      - Command Reference: commands.md

# ------------------------------------------------------------
#  Markdown Extensions (for advanced formatting & features)
# ------------------------------------------------------------
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list
  - md_in_html
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar
  - pymdownx.arithmatex:
      generic: true

# ------------------------------------------------------------
#  Plugins
# ------------------------------------------------------------
plugins:
  - search
  - tags
  - mermaid2

# ------------------------------------------------------------
#  Extra configuration (footer & social links)
# ------------------------------------------------------------
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FahimFBA
      name: FahimFBA on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mdfahimbinamin/
      name: LinkedIn
  generator: false
  copyright: >
    © 2025 Md. Fahim Bin Amin. Licensed under the MIT License.

# ------------------------------------------------------------
#  Exclude files from documentation build
# ------------------------------------------------------------
exclude_docs: |
  README.md
  LICENSE
